In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
arr1=arr.reshape(2,3)
print(arr1)
arr1.reshape(3,2)


In [ ]:
a1=np.array([[1,2],[1,2],[1,2]])
a1.shape

In [ ]:
np.random.rand(4,2)

In [ ]:
np.full([2,3],"1")

In [ ]:
np.ones([1,2])
np.ones_like([1,2])
# np.zeros([1,2])

In [ ]:
np.arange(2,8,2)

In [ ]:
np.array([10,3,5])**2

In [ ]:
np.array([1,2,3,4,5,6,7,8]).reshape([2,4])

In [ ]:
np.array([1,2,3,4,5,6,7,8]).reshape([2,4]).flatten()

In [42]:
for i in np.array([5,6]):
    print(i)

5
6


In [ ]:
a2=np.ones((5,))
print(a2.shape)
a2=a2[np.newaxis,:]#same as None
print(a2.shape)
a2=a2[None,:]
a2.shape


In [55]:
a3=np.array([1,2,3,4,5,])
print(a3>3)
a3=np.array((1,2,3,4,5,))
print(a3>3)
a3[a3>3]

[False False False  True  True]
[False False False  True  True]


array([4, 5])

In [57]:
a4=np.array([1,2,3,4,5,6,7])
a4[2:4]

array([3, 4])

In [ ]:
first=np.array([[1,2,3,4],[4,5,6,7]])
second=np.array([[1,2,3],[4,5,6]])
np.hstack((first,second))#no of rows will be same as old array

array([[1, 2, 3, 4, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6]])

In [ ]:
first=np.array([[1,2,3,4],[4,5,6,7]])
second=np.array([[1,2,3,3],[4,5,6,3]])
np.vstack((first,second))#additional rows

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 3],
       [4, 5, 6, 3]])

In [72]:
arr=np.arange(1,11)
print(arr)
print(np.split(arr,2))
print(np.split(arr,5))

[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
